### ISSUE TITLE
Tainted Canvas after using Get Image

### ISSUE THREAD

**Issue by arnavthareja** [evilpegasus/Yearbook#1]
After pressing the Get Image button, uploading the canvas no longer works and returns the message "Tainted canvases may not be exported"

**Comment by arnavthareja** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by arnavthareja** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by evilpegasus** [comment]
fixed

**Comment by arnavthareja** [comment]
Used workaround
