### ISSUE TITLE
Broken button in Navigation

### ISSUE THREAD

**Issue by garytou2** [evilpegasus/Yearbook#3]
The "Someone Else's Yearbook" button does not work on the following pages
- Frequently Asked Questions (FAQ)
- About Yearbook 2020

> popup.js:114 Uncaught TypeError: Cannot read property 'style' of null
    at openPromptPopup (popup.js:114)
    at goToAnotherYearbook (menu.js:24)
    at HTMLButtonElement.onclick (about.html:60)

**Comment by evilpegasus** [comment]
Fixed with
https://github.com/evilpegasus/Yearbook/commit/ca577a533f8e24356c669d3f7628e6398d4a68bb
